common:
  name: "基础信息管理"
  default_path: "/period_prices"
  submenus:
    period_prices_path: "时段价格管理"
    cards_path:  "卡模板管理"
    courts_path: "场地管理" 
    vacations_path: "节假日管理"
    coaches_path: "教练管理"
    list_lockers_path: "储物柜管理"
    
member:
  name: "会员管理"
  default_path: "/members"
  submenus:

member_card:
  name: "会员卡管理"
  default_path: "/members_cards/new"
  submenus:

book_record:
  name: "场地预定"
  default_path: "/orders"
  submenus:

goods:
  name: "库存管理"
  default_path: "/goods"
  submenus:

report:
  name: "分析报表"
  default_path: "/reports/income"
  submenus:

balance:
  name: "消费结算"
  default_path: "/balances/new_good_buy"
  submenus:

locker:
  name: "储物柜"
  default_path: "/lockers"
  submenus:

authorize:
  name: "权限管理"
  default_path: "/users"
  submenus:

system:
  name: "系统管理"
  default_path: "/logs"
  submenus:
